### ISSUE TITLE
Unable to go to /auth-live/admin after activation

### ISSUE THREAD

**Issue by yukzanaly** [humhub-contrib/auth-microsoft#2]
Install module successful and can activate. but once I click the configuration button, humhub shows error 

this's what on the log:

yii\di\NotInstantiableException
ReflectionException: Class "humhubContrib\auth\microsoft\Module" does not exist in /home/public_html/protected/vendor/yiisoft/yii2/di/Container.php:507

**Comment by ArchBlood** [comment]
Looks to be because of the following lines?

https://github.com/humhub-contrib/auth-microsoft/blob/main/Module.php#L36-L60

**Comment by ArchBlood** [comment]
Also should change `live` on this line to `microsoft`

https://github.com/humhub-contrib/auth-microsoft/blob/main/Module.php#L24
