### ISSUE TITLE
Dynamic entries can lead to internal server error

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/auth-microsoft#4]
I've noticed a possible issue in the following code;
https://github.com/humhub-contrib/auth-microsoft/blob/84dc6abc51d0902fba3cf360b7c918fbe8ee904c/Module.php#L36-L60

The current implementation edits and adds the entry to `/protected/config/dynamic.php` if any changes are done manually to the module itself, it can cause the module to make the site throw an internal server error.

**Comment by ArchBlood** [comment]
Possible solution would be creating another class called `CommonConfig` which enters the information into the `common.php` instead of doing  this dynamically.

**Comment by ArchBlood** [comment]
Other option would be doing this in the `config.php`
```php
'rules' => [
    // Rules needed applied
]
```

**Comment by ArchBlood** [comment]
Okay, so in theory the following changes need made and it should work;

### `Module.php`
This needs completely removed;
https://github.com/humhub-contrib/auth-microsoft/blob/84dc6abc51d0902fba3cf360b7c918fbe8ee904c/Module.php#L36-L60

### `Events.php`
Remove this line;
https://github.com/humhub-contrib/auth-microsoft/blob/84dc6abc51d0902fba3cf360b7c918fbe8ee904c/Events.php#L25

### `ConfigureForm.php`
Update this to match the `config.php`
https://github.com/humhub-contrib/auth-microsoft/blob/84dc6abc51d0902fba3cf360b7c918fbe8ee904c/models/ConfigureForm.php#L81

### `config.php`
Change this;
https://github.com/humhub-contrib/auth-microsoft/blob/84dc6abc51d0902fba3cf360b7c918fbe8ee904c/config.php#L1-L12
To this;
```php
<?php

use humhub\modules\user\authclient\Collection;
use yii\web\UrlRule;

return [
    'id' => 'auth-microsoft',
    'class' => 'humhubContrib\auth\microsoft\Module',
    'namespace' => 'humhubContrib\auth\microsoft',
    'events' => [
        [Collection::class, Collection::EVENT_AFTER_CLIENTS_SET, ['humhubContrib\auth\microsoft\Events', 'onAuthClientCollectionInit']]
    ],
    'rules' => [
        [
            'class' => UrlRule::class,
            'pattern' => '/user/auth/microsoft',
            'route' => '/user/auth/external',
            'defaults' => [
                'authclient' => 'microsoft'
            ]
        ],
    ],
];
```

**Comment by ArchBlood** [comment]
Doing this should comply with Microsoft query parameter support within redirect URIs.
https://learn.microsoft.com/en-us/entra/identity-platform/reply-url#query-parameter-support-in-redirect-uris

**Comment by luke-** [comment]
Yes, the URL Routing should definitly done via `config.php`

**Comment by ArchBlood** [comment]
Would you like me to do this in the existing #3 or open a new P/R?

**Comment by luke-** [comment]
Happy to work in existing PR.

**Comment by ArchBlood** [comment]
> Happy to work in existing PR.

Done. 😄

**Comment by luke-** [comment]
Thanks should I merge the PR?

**Comment by ArchBlood** [comment]
> Thanks should I merge the PR?

Yes, it seems to be working as intended now.
